### ISSUE TITLE
Crash when trying to create a card. Is this the place to post?

### ISSUE THREAD

**Issue by WestCoastErik** [ll-in-anki/anki-LL#10]
> Error 
>
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
>
> If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
>
> When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
```
Debug info:
Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.15.2
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Find Missing Words

Caught exception:
  File "/Users/erikgiddings/Library/Application Support/Anki2/addons21/754868802/gui/search_results/note_creation.py", line 285, in create_note_from_preset
    self.editor = add_note_widget.AddNoteWidget(mw, note, self.on_note_add, self.on_note_cancel, parent=self)
  File "/Users/erikgiddings/Library/Application Support/Anki2/addons21/754868802/gui/search_results/add_note_widget.py", line 33, in __init__
    addCloseShortcut(self)
  File "aqt/utils.py", line 416, in addCloseShortcut
<class 'AttributeError'>: 'AddNoteWidget' object has no attribute 'reject'
```

**Comment by cofinley** [comment]
Yep this is the right place! Thanks for bringing it up. We’ll look into that. Appreciated the error readout, too!
