### ISSUE TITLE
Add image search

### ISSUE THREAD

**Issue by ghost** [ll-in-anki/anki-LL#11]
A few days ago a user asked ssricardo (the author of the "Web Browser" add-on) to implement a way to search for multiple words in a sentence ( https://github.com/ssricardo/anki-plugins/issues/35 ) specifically referring to your add-on.

ssricardo replied that would take some major changes to his code; do you think it would be easier for you to implement something like that?

Thanks

**Comment by cofinley** [comment]
Hi @lang-learner, 

Indeed, that would be a large undertaking for the web browser addon.

This is something we’re planning on doing, but in a new addon. We thought about bundling it in with this one, but by creating a new addon that only deals with images, audio, etc., we can separate concerns and not lock users into one way of doing things. This addon has already gotten complex enough :)

The new addon will most likely extend the functionality of the Anki note editor. In this way, users of this addon would get image/audio search as soon as they start creating a new note and populate the fields. Others who would just have the new addon would still be able to enjoy its functionality.

We hope to start work on it soon, as this is a big desire of ours as well. We also encourage anyone who’s interested in collaborating to join the GH ll-in-anki organization and get in touch!
